#!/bin/bash
GREEN="\\033[1;32m"
NORMAL="\\033[0;39m"
RED="\\033[1;31m"
PINK="\\033[1;35m"
BLUE="\\033[1;34m"
WHITE="\\033[0;02m"
BLANCLAIR="\\033[1;08m"
YELLOW="\\033[1;33m"
CYAN="\\033[1;36m"

echo -e "$GREEN" "------------------ ""$RED"" FRONT-END test v0.1 ""$GREEN""  ------------------""$NORMAL"
rm ./client/main_test.js
cat ./client/test/main_test_begin.txt >> ./client/main_test.js
nbTests=`find ./client -name "test-*.js" | wc -l`
nbLine=1
for line in `find ./client -name "test-*.js"`; do
	if [ "$nbLine" -eq "$nbTests" ]; then
		echo "'$line'" >> ./client/main_test.js
	else
		echo "'$line'," >> ./client/main_test.js
	fi
	nbLine=$((nbLine+1))
done
echo "]);})();" >> ./client/main_test.js
phantomjs client/modules/tests.js
echo -e "$GREEN" "------------------------------©focusmatic------------------""$NORMAL"