#!/bin/bash
# Copyright © 2012, Focusmatic SAS

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the
# following conditions:

# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
# NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
# USE OR OTHER DEALINGS IN THE SOFTWARE.

GREEN="\\033[1;32m"
NORMAL="\\033[0;39m"
RED="\\033[1;31m"

echo -e "$GREEN" "------------------ ""$RED"" FRONT-END test v0.1 ""$GREEN""  ------------------""$NORMAL"
cd client
# rm ./client/main_test.js
rm ./main_test.js
# cat ./client/test/main_test_begin.txt >> ./client/main_test.js
cat ./test/main_test_begin.txt >> ./main_test.js
# nbTests=`find ./client -name "test-*.js" | wc -l`
nbTests=`find . -name "test-*.js" | wc -l`
nbLine=1
for line in `find . -name "test-*.js"`; do
	if [ "$nbLine" -eq "$nbTests" ]; then
		echo "'$line'" >> ./main_test.js
	else
		echo "'$line'," >> ./main_test.js
	fi
	nbLine=$((nbLine+1))
done
echo "]);});" >> ./main_test.js
phantomjs ./modules/test/phantom-test-script.js
echo -e "$GREEN" "------------------------------©focusmatic------------------""$NORMAL"